name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
    paths:
      - src/main/riddl/**


jobs:
  make-gh-pages:
    name: Generate GH Pages From RIDDL Sources
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.100.2'
          extended: true

      - name: Show Hugo on PATH
        run: 'which hugo'
        
      - name: Generate Hugo From RIDDL
        uses: reactific/riddl-actions@v0.3.5
        with:
          command: from 
          opt1: src/main/riddl/ImprovingApp.conf
          opt2: -H
          opt3: /home/runner/actions_hugo/bin/hugo

      - name: Generate HTML From Hugo
        run: cd target/hugo ; hugo --minify -D -v --printMemoryUsage

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/hugo/public
