name: Validate RIDDL

on:
  push:
    branches: [ main, Kalix-Study ]
  pull_request:
    branches: [ main, Kalix-Study ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Get riddlc
      uses: reactific/riddl/actions/get-riddlc@main
    - name: Validate improving-app model with riddlc
      run: |
        echo RIDDLC = "$RIDDLC"
        which riddlc
        riddlc from "src/main/riddl/ImprovingApp.conf" validate
      shell: bash
